### ISSUE TITLE
How to handle `that was originally registered here. Are you missing a call to unregisterReceiver()?`

### ISSUE THREAD

**Issue by zhiephie** [probelalkhan/android-sqlite-mysql-sync-example#3]
```
09-12 13:34:27.027 14714-14714/net.simplifiedcoding.androidmysqlsync E/ActivityThread: Activity net.simplifiedcoding.androidmysqlsync.MainActivity has leaked IntentReceiver net.simplifiedcoding.androidmysqlsync.NetworkStateChecker@9e7adda that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                       android.app.IntentReceiverLeaked: Activity net.simplifiedcoding.androidmysqlsync.MainActivity has leaked IntentReceiver net.simplifiedcoding.androidmysqlsync.NetworkStateChecker@9e7adda that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                           at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:920)
                                                                                           at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:721)
                                                                                           at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1182)
                                                                                           at android.app.ContextImpl.registerReceiver(ContextImpl.java:1162)
                                                                                           at android.app.ContextImpl.registerReceiver(ContextImpl.java:1156)
                                                                                           at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:564)
                                                                                           at net.simplifiedcoding.androidmysqlsync.MainActivity.onCreate(MainActivity.java:75)
                                                                                           at android.app.Activity.performCreate(Activity.java:6303)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
09-12 13:34:27.031 14714-14714/net.simplifiedcoding.androidmysqlsync E/ActivityThread: Activity net.simplifiedcoding.androidmysqlsync.MainActivity has leaked IntentReceiver net.simplifiedcoding.androidmysqlsync.MainActivity$1@ef02b01 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                       android.app.IntentReceiverLeaked: Activity net.simplifiedcoding.androidmysqlsync.MainActivity has leaked IntentReceiver net.simplifiedcoding.androidmysqlsync.MainActivity$1@ef02b01 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                           at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:920)
                                                                                           at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:721)
                                                                                           at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1182)
                                                                                           at android.app.ContextImpl.registerReceiver(ContextImpl.java:1162)
                                                                                           at android.app.ContextImpl.registerReceiver(ContextImpl.java:1156)
                                                                                           at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:564)
                                                                                           at net.simplifiedcoding.androidmysqlsync.MainActivity.onCreate(MainActivity.java:102)
                                                                                           at android.app.Activity.performCreate(Activity.java:6303)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                                                           at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

```

**Comment by zhiephie** [comment]
Can u help me @probelalkhan

**Comment by Dipak26** [comment]
@zhiephie  You need to unRegisterReceiver used Receiver in onStop Method of activity.
